<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <PyPath>$(ProjectDir)../pysabberstone-pythonnet/pysabberstone/lib</PyPath>
	  <AssemblyVersion>8.0.0.2</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
  	<EmbeddedResource Include="resources\Data\CardDefs.xml">
	    <LogicalName>SabberStoneCore.Resources.CardDefs.xml</LogicalName>
  	</EmbeddedResource>
    <EmbeddedResource Include="resources\Data\CardDefs-36393.xml">
	    <LogicalName>SabberStoneCore.Resources.CardDefs-36393.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="resources\Data\CardDefs-36393-Classics.xml">
	    <LogicalName>SabberStoneCore.Resources.CardDefs-36393-Classics.xml</LogicalName>
    </EmbeddedResource>
  	<EmbeddedResource Include="resources\Data\PlayErrors.xml">
  		<LogicalName>SabberStoneCore.Resources.PlayErrors.xml</LogicalName>
  	</EmbeddedResource>
  </ItemGroup>

	<Target Name="CopyDLLToPy" AfterTargets="Build" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PyPath)" />
	</Target>

</Project>
