#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using SabberStoneCore.Enchants;
using SabberStoneCore.Enums;
using SabberStoneCore.Kettle;
using SabberStoneCore.Loader;
using SabberStoneCore.Tasks.PlayerTasks;
using SabberStoneCore.Model.Zones;
// ReSharper disable CoVariantArrayConversion

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// Instance that represents a player in SabberStone game instances.
	/// <seealso cref="Entity"/>
	/// </summary>
	public partial class Controller : Entity
	{
		/// <summary>
		/// Maximum amount of cards in the player's hand
		/// </summary>
		public const int MaxHandSize = 10;

		/// <summary>
		/// Maximum amount of mana this player is allowed to spend.
		/// </summary>
		public const int MaxResources = 10;

		/// <summary>
		/// Available zones for this player.
		/// </summary>
		public ControlledZones ControlledZones;

		/// <summary>
		/// The deck of this player.
		/// This zone contains cards which are not yet drawn. Can be empty.
		/// </summary>
		public DeckZone DeckZone;

		/// <summary>
		/// The hand of this player.
		/// This zone contains cards which were drawn from deck or generated.
		/// during the game. Can be empty.
		/// </summary>
		public HandZone HandZone;

		/// <summary>
		/// The minions friendly to this player.
		/// This zone contains all minion entities generated by cards from the hand.
		/// Can be empty.
		/// </summary>
		public BoardZone BoardZone;

		/// <summary>
		/// The zone containing all entities which were once in play, but now destroyed. Can be empty.
		/// </summary>
		public GraveyardZone GraveyardZone;

		/// <summary>
		/// The zone containing all played secrets by this player. Can be empty.
		/// </summary>
		public SecretZone SecretZone;

		/// <summary>
		/// The zone containing all entities that need to be chosen by the player.
		/// Before an option set is created, it's entities are built and stored in the this zone.
		/// The picked entity will move from that zone into the hand zone.
		///
		/// Unpicked entities will remain in the setaside zone.
		/// </summary>
		public SetasideZone SetasideZone;

		public readonly List<int> DiscardedEntities;
		public readonly List<Card> CardsPlayedThisTurn;
		public readonly List<PlayHistoryEntry> PlayHistory;

		/// <summary>
		/// Name of the player.
		/// </summary>
		public string Name { get; }

		/// <summary>
		/// Initial cards that are in the deck of the controller.
		/// </summary>
		public List<Card> DeckCards { get; internal set; }

		/// <summary>
		/// Base class of the controller.
		/// </summary>
		public CardClass BaseClass { get; internal set; }


		/// <summary>
		/// The hero entity representing this player.
		/// </summary>
		public HeroInPlay Hero { get; set; }

		/// <summary>
		/// The cardclass of the deck.
		/// Only neutral cards and cards specific to this class are allowed in the starting deck
		/// of the player.
		/// </summary>
		public CardClass HeroClass => Hero.Card.Class;

		/// <summary>
		/// All standard cards which can be put into a deck of this class.
		/// </summary>
		public IReadOnlyList<Card> Standard => Cards.Standard[HeroClass];

		/// <summary>
		/// All wild cards which can be put into a deck of this class.
		/// </summary>
		public IReadOnlyList<Card> Wild => Cards.Wild[HeroClass];

		/// <summary>
		/// The amount of mana available to actually use after calculating all resource factors.
		/// </summary>
		public int RemainingMana => BaseMana + TemporaryMana - (UsedMana + OverloadLocked);

		/// <summary>
		/// Returns true if this player has a dragon in his hand.
		/// </summary>
		public bool DragonInHand => HandZone.Any(p => p.Card.IsRace(Race.DRAGON));

		//public bool TemporusFlag { get; set; }

		/// <summary>
		/// The last choice set proposed to this player.
		/// The actual chosen entity is also stored in the Choice object.
		/// </summary>
		public Choice Choice { get; set; }

        /// <summary>
        /// The opponent player instance.
        /// </summary>
        public Controller Opponent { get; internal set;}

        /// <summary>
		/// Create a new controller instance.
		/// </summary>
		/// <param name="game">The game to which it registers.</param>
		/// <param name="name">The name of the player.</param>
		/// <param name="playerId">The player index; The first player will get assigned 1.</param>
		/// <param name="id">Entity ID of this controller.</param>
		public Controller(Game game, string name, int playerId, int id)
			: base(in game, Card.CardPlayer, in id)
		{
			Name = name;
			PlayerId = playerId;
			Controller = this;

			DeckZone = new DeckZone(this);
			BoardZone = new BoardZone(this);
			HandZone = new HandZone(this);
			SecretZone = new SecretZone(this);
			GraveyardZone = new GraveyardZone(this);
			SetasideZone = new SetasideZone(this);

			ControlledZones = new ControlledZones(this);

			DeckCards = new List<Card>(30);
			DiscardedEntities = new List<int>();
			CardsPlayedThisTurn = new List<Card>(10);
			//cardsPlayedThisGame = new List<Card>(30);
			PlayHistory = new List<PlayHistoryEntry>(30);
			
			Game.Log(LogLevel.INFO, BlockType.PLAY, "Controller", !Game.Logging? "":$"Created Controller '{name}'");
		}

		/// <summary>
		/// A copy constructor.
		/// </summary>
		/// <param name="game">The target <see cref="Game"/> instance.</param>
		/// <param name="controller">The source <see cref="Controller"/></param>
		private Controller(in Game game, in Controller controller) : base(in game, controller)
		{
			Name = controller.Name;

			Controller = this;

			Hero = (HeroInPlay)controller.Hero.Clone(this);

			Hero.HeroPower = (HeroPower)controller.Hero.HeroPower.Clone(this);

			if (controller.Hero.Weapon != null)
			{
				Hero.Weapon = (Weapon)controller.Hero.Weapon.Clone(this);
			}

			Choice = controller.Choice?.Clone(this);

			BoardZone = new BoardZone(this);
			SetasideZone = controller.SetasideZone.Clone(this);
			DeckZone = controller.DeckZone.Clone(this);
			HandZone = controller.HandZone.Clone(this);
			GraveyardZone = controller.GraveyardZone.Clone(this);
			SecretZone = controller.SecretZone.Clone(this);
			controller.BoardZone.Stamp(BoardZone);

			Hero.Zone = BoardZone;

			DeckCards = controller.DeckCards;
			BaseClass = controller.BaseClass;

			ControlledZones = new ControlledZones(this);

			PlayHistory = new List<PlayHistoryEntry>(controller.PlayHistory);
			DiscardedEntities = new List<int>(controller.DiscardedEntities);
			CardsPlayedThisTurn = new List<Card>(controller.CardsPlayedThisTurn);

			_attrs = controller._attrs;
		}

		/// <summary>
		/// Performs a deep copy of this <see cref="Controller"/> instance and returns the result.
		/// Copied instance and all entities in its zones are deep copied to the target <see cref="Game"/> instance.
		/// </summary>
		/// <param name="game">The target Game.</param>
		/// <returns></returns>
		public Controller Clone(in Game game)
		{
			return new Controller(in game, this);
		}

		/// <summary>
		/// Adds a new Hero entity and HeroPower entity to the game instance.
		/// </summary>
		/// <param name="heroCard">The card to derive the hero entity from.</param>
		/// <param name="powerCard">The heropower card to derive the hero power entity from.</param>
		/// <param name="tags">The inherited tags</param>
		/// <param name="id">The entity id to assign to the generated HERO entity</param>
		public void AddHeroAndPower(in Card heroCard, in Card powerCard = null, in EntityData tags = null, in int id = -1)
		{
			// remove hero and place it to the setaside zone
			Weapon weapon = null;
			//AuraEffects auraEffects = null;
			if  (Hero != null)
			{
				SetasideZone.MoveTo(Hero);
				SetasideZone.MoveTo(Hero.HeroPower);
				//Hero[GameTag.EXHAUSTED] = 0;
				//Hero[GameTag.NUM_ATTACKS_THIS_TURN ] = 0;
				//Hero[GameTag.DAMAGE] = 0;
				//Hero.IsRevealed = true;
				if (Hero.Weapon != null)
				{
					weapon = Hero.Weapon;
				}

				//auraEffects = Hero.AuraEffects;
			}


			//Hero = (Hero) FromCard(this, in heroCard, tags, null, id);
			Hero = HeroInPlay.FromCard(this, in heroCard);
			if (Game.History)
				Hero[GameTag.ZONE] = (int) Enums.Zone.PLAY;
			HeroId = Hero.Id;
			Hero.HeroPower = FromCard(this, powerCard ?? Cards.FromAssetId(Hero[GameTag.HERO_POWER]), creator: Hero) as HeroPower;
			Hero.Weapon = weapon;
			//Hero.AuraEffects = auraEffects;
		}

		/// <summary>
		/// Build a unique string describing this object.
		/// </summary>
		/// <param name="ignore">All GameTags which have to be ignored during hash generation.</param>
		/// <returns>The unique hash string.</returns>
		public override string Hash(params GameTag[] ignore)
		{
			var str = new StringBuilder();
			str.Append("[C:");
			str.Append(Name);
			str.Append("]");
			str.Append(base.Hash(ignore));
			str.Append(Hero.Hash(ignore));
			str.Append(Hero.HeroPower.Hash(ignore));
			if (Hero.Weapon != null)
				str.Append(Hero.Weapon.Hash(ignore));
			str.Append(ControlledZones.Hash(ignore));
			return str.ToString();
		}

		/// <summary>
		/// Returns a set of all options this player can perform execute at the moment.
		/// From this set one option is picked and executed by the game.
		/// </summary>
		/// <param name="skipPrePhase">Doesn't check validity of the options generated from this when it is processed.</param>
		/// <returns></returns>
		public List<PlayerTask> Options(bool skipPrePhase = true)
		{
			// No options for the opponent player.
			if (this != Game.CurrentPlayer)
				return new List<PlayerTask>(0);

			//	ChooseTasks
			if (Choice != null)
			{
				switch (Choice.ChoiceType)
				{
					case ChoiceType.GENERAL:
						return Choice.Choices.Select(p => (PlayerTask)ChooseTask.Pick(this, p)).ToList();

					case ChoiceType.MULLIGAN:
						IEnumerable<IEnumerable<int>> choices = Util.GetPowerSet(Choice.Choices);
						return choices.Select(p => (PlayerTask) ChooseTask.Mulligan(this, p.ToList())).ToList();

					default:
						throw new NotImplementedException();
				}
			}

			// no options till mulligan is done for both players
			if (Game.Step != Step.MAIN_ACTION)
				return new List<PlayerTask>(0);

			//	EndTurnTask
			var allOptions = new List<PlayerTask>(20) { EndTurnTask.Any(this) };

			#region PlayCardTasks
			int mana = RemainingMana;
			int zonePosRange = BoardZone.Count;
			bool? spellCostHealth = null;

			Character[] allTargets = null;
			Minion[] friendlyMinions = null;
			Minion[] enemyMinions = null;
			Minion[] allMinions = null;
			Character[] allFriendly = null;
			Character[] allEnemies = null;

			ReadOnlySpan<Playable> handSpan = HandZone.GetSpan();
			for (int i = 0; i < handSpan.Length; i++)
			{
				if (!handSpan[i].ChooseOne || ChooseBoth)
					GetPlayCardTasks(handSpan[i]);
				else
				{
					Playable[] playables = handSpan[i].ChooseOnePlayables;
					for (int j = 1; j < 3; j++)
						GetPlayCardTasks(handSpan[i], playables[j - 1], j);
				}
			}
			#endregion

			#region HeroPowerTask
			HeroPower power = Hero.HeroPower;
			Card heroPowerCard = power.Card;
			if (!power.IsExhausted && mana >= power.Cost &&
			    !HeroPowerDisabled && !heroPowerCard.HideStat)
			{
				if (heroPowerCard.ChooseOne)
				{
					if (ChooseBoth)
						allOptions.Add(HeroPowerTask.Any(this, skipPrePhase: true));
					else
					{
						allOptions.Add(HeroPowerTask.Any(this, null, 1, true));
						allOptions.Add(HeroPowerTask.Any(this, null, 2, true));
					}
				}
				else
				{
					if (heroPowerCard.IsPlayableByCardReq(this))
					{
						Character[] targets = GetTargets(heroPowerCard);
						if (targets != null)
							for (int i = 0; i < targets.Length; i++)
								allOptions.Add(HeroPowerTask.Any(this, targets[i], skipPrePhase: true));
						else
							allOptions.Add(HeroPowerTask.Any(this, skipPrePhase: true));
					}
				}
			}
			#endregion

			#region MinionAttackTasks
			Minion[] attackTargets = null;
			bool isOpHeroValidAttackTarget = false;
			ReadOnlySpan<MinionInPlay> boardSpan = BoardZone.GetSpan();
			for (int j = 0; j < boardSpan.Length; j++)
			{
				MinionInPlay minion = boardSpan[j];

				//if (minion.IsExhausted && (!minion.HasCharge || minion.NumAttacksThisTurn != 0))
				//	continue;
				//if (minion.IsFrozen || minion.AttackDamage == 0 || minion.CantAttack || minion.Untouchable)
				//	continue;

				if (!minion.CanAttack(false)) continue;

				GenerateAttackTargets();

				for (int i = 0; i < attackTargets.Length; i++)
					allOptions.Add(MinionAttackTask.Any(this, minion, attackTargets[i], skipPrePhase));

				if (isOpHeroValidAttackTarget && !(minion.CantAttackHeroes || minion.AttackableByRush))
					allOptions.Add(MinionAttackTask.Any(this, minion, Opponent.Hero, skipPrePhase));
			}
			#endregion

			#region HeroAttackTaskts
			HeroInPlay hero = Hero;

			if (!hero.IsExhausted && hero.AttackDamage > 0 && !hero.IsFrozen)
			{
				GenerateAttackTargets();

				for (int i = 0; i < attackTargets.Length; i++)
					allOptions.Add(HeroAttackTask.Any(this, attackTargets[i], skipPrePhase));

				if (isOpHeroValidAttackTarget && !hero.CantAttackHeroes)
					allOptions.Add(HeroAttackTask.Any(this, Opponent.Hero, skipPrePhase));
			}
			#endregion

			return allOptions;

			#region local functions
			void GetPlayCardTasks(in Playable playable, in Playable chooseOnePlayable = null, int subOption = -1)
			{
				Card card = chooseOnePlayable?.Card ?? playable.Card;

				if (!spellCostHealth.HasValue)
					spellCostHealth = SpellsCostHealth;

				bool healthCost = (playable.CardCostsHealth) ||
				                  (spellCostHealth.Value && playable.Card.Type == CardType.SPELL);

				if (!healthCost && (playable.Cost > mana || playable.Card.HideStat))
					return;

				// check PlayableByPlayer
				switch (playable.Card.Type)
				{
					//	REQ_MINION_CAP
					case CardType.MINION when BoardZone.IsFull:
						return;
					case CardType.SPELL:
					{
						if (card.IsSecret)
						{
							if (SecretZone.IsFull) // REQ_SECRET_CAP
								return;

							{
								ReadOnlySpan<Spell> span = SecretZone.GetSpan();
								for (int i = 0; i < span.Length; ++i)
									if (span[i].Card.AssetId == card.AssetId)  // REQ_UNIQUE_SECRET
										return;
							}
						}

						if (card.IsQuest && SecretZone.Quest != null)
							return;
						break;
					}
				}

				{
					if (!card.IsPlayableByCardReq(this))
						return;

					Character[] targets = GetTargets(card);

					// Card doesn't require any targets
					if (targets == null)
					{
						if (playable is Minion)
							for (int i = 0; i <= zonePosRange; i++)
								allOptions.Add(PlayCardTask.Any(this, playable, null, i, subOption, skipPrePhase));
						else
							allOptions.Add(PlayCardTask.Any(this, playable, null, -1, subOption, skipPrePhase));
					}
					else
					{
						if (targets.Length == 0)
						{
							if (card.MustHaveTargetToPlay)
								return;

							if (playable is Minion)
								for (int i = 0; i <= zonePosRange; i++)
									allOptions.Add(PlayCardTask.Any(this, playable, null, i, subOption, skipPrePhase));
							else
								allOptions.Add(PlayCardTask.Any(this, playable, null, -1, subOption, skipPrePhase));
						}
						else
						{
							for (int j = 0; j < targets.Length; j++)
							{
								Character target = targets[j];
								if (playable is Minion)
									for (int i = 0; i <= zonePosRange; i++)
										allOptions.Add(PlayCardTask.Any(this, playable, target, i, subOption,
											true));
								else
									allOptions.Add(PlayCardTask.Any(this, playable, target, -1, subOption, skipPrePhase));

							}
						}
					}
				}
			}

			// Returns null if targeting is not required
			// Returns 0 Array if there is no available target
			Character[] GetTargets(Card card)
			{
				// Check it needs additional validation
				if (!card.TargetingAvailabilityPredicate?.Invoke(this) ?? false)
					return null;

				Character[] targets;

				switch (card.TargetingType)
				{
					case TargetingType.None:
						return null;
					case TargetingType.All:
						if (allTargets == null)
						{
							if (Opponent.Hero.HasStealth || Opponent.Hero.IsImmune)
							{
								allTargets = new Character[GetFriendlyMinions().Length + GetEnemyMinions().Length + 1];
								allTargets[0] = Hero;
								Array.Copy(GetAllMinions(), 0, allTargets, 1, allMinions.Length);
							}
							else
							{
								allTargets = new Character[GetFriendlyMinions().Length + GetEnemyMinions().Length + 2];
								allTargets[0] = Hero;
								allTargets[1] = Opponent.Hero;
								Array.Copy(GetAllMinions(), 0, allTargets, 2, allMinions.Length);
							}
						}
						targets = allTargets;
						break;
					case TargetingType.FriendlyCharacters:
						if (allFriendly == null)
						{
							allFriendly = new Character[GetFriendlyMinions().Length + 1];
							allFriendly[0] = Hero;
							Array.Copy(friendlyMinions, 0, allFriendly, 1, friendlyMinions.Length);
						}
						targets = allFriendly;
						break;
					case TargetingType.EnemyCharacters:
						if (allEnemies == null)
						{
							if (!Opponent.Hero.HasStealth || Opponent.Hero.IsImmune)
							{
								allEnemies = new Character[GetEnemyMinions().Length + 1];
								allEnemies[0] = Opponent.Hero;
								Array.Copy(enemyMinions, 0, allEnemies, 1, enemyMinions.Length);
							}
							else
								allEnemies = GetEnemyMinions();
						}
						targets = allEnemies;
						break;
					case TargetingType.AllMinions:
						targets = GetAllMinions();
						break;
					case TargetingType.FriendlyMinions:
						targets = GetFriendlyMinions();
						break;
					case TargetingType.EnemyMinions:
						targets = GetEnemyMinions();
						break;
					case TargetingType.Heroes:
						targets = !Opponent.Hero.HasStealth
							? new[] { Hero, Opponent.Hero }
							: new[] { Hero };
						break;
					default:
						throw new ArgumentOutOfRangeException();
				}

				// Filtering for target_if_available
				TargetingPredicate p = card.TargetingPredicate;
				if (p != null)
				{
					if (card.Type == CardType.SPELL || card.Type == CardType.HERO_POWER)
					{
						Character[] buffer = new Character[targets.Length];
						int i = 0;
						for (int j = 0; j < targets.Length; ++j)
						{
							if (!p(targets[j]) || targets[j].CantBeTargetedBySpells) continue;
							buffer[i] = targets[j];
							i++;
						}

						if (i != targets.Length)
						{
							Character[] result = new Character[i];
							Array.Copy(buffer, result, i);
							return result;
						}
						return buffer;
					}
					else
					{
						//if (!card.TargetingAvailabilityPredicate?.Invoke(this, card) ?? false)
						//	return null;

						Character[] buffer = new Character[targets.Length];
						int i = 0;
						for (int j = 0; j < targets.Length; ++j)
						{
							if (!p(targets[j])) continue;
							buffer[i] = targets[j];
							i++;
						}

						if (i != targets.Length)
						{
							Character[] result = new Character[i];
							Array.Copy(buffer, result, i);
							return result;
						}
						return buffer;
					}
				}
				else if (card.Type == CardType.SPELL || card.Type == CardType.HERO_POWER)
				{
					Character[] buffer = new Character[targets.Length];
					int i = 0;
					for (int j = 0; j < targets.Length; ++j)
					{
						if (targets[j].CantBeTargetedBySpells) continue;
						buffer[i] = targets[j];
						i++;
					}

					if (i != targets.Length)
					{
						Character[] result = new Character[i];
						Array.Copy(buffer, result, i);
						return result;
					}
					return buffer;
				}

				return targets;

				Minion[] GetFriendlyMinions()
				{
					return friendlyMinions ?? (friendlyMinions = BoardZone.GetAll());
				}

				Minion[] GetAllMinions()
				{
					if (allMinions != null)
						return allMinions;

					allMinions = new Minion[GetEnemyMinions().Length + GetFriendlyMinions().Length];
					Array.Copy(enemyMinions, allMinions, enemyMinions.Length);
					Array.Copy(friendlyMinions, 0, allMinions, enemyMinions.Length, friendlyMinions.Length);

					return allMinions;
				}
			}

			void GenerateAttackTargets()
			{
				if (attackTargets != null) return;

				Minion[] eMinions = GetEnemyMinions();
				//var taunts = new Minion[eMinions.Length];
				Minion[] taunts = null;
				int tCount = 0;
				for (int i = 0; i < eMinions.Length; i++)
					if (eMinions[i].HasTaunt)
					{
						if (taunts == null)
							taunts = new Minion[eMinions.Length];
						taunts[tCount] = eMinions[i];
						tCount++;
					}

				if (tCount > 0)
				{
					var targets = new Minion[tCount];
					Array.Copy(taunts, targets, tCount);
					attackTargets = targets;
					isOpHeroValidAttackTarget = false;  // some brawls allow taunt heros and this should be fixed
					return;
				}
				attackTargets = eMinions;

				isOpHeroValidAttackTarget =
					!Opponent.Hero.IsImmune && !Opponent.Hero.HasStealth;
			}

			Minion[] GetEnemyMinions()
			{
				return enemyMinions ?? (enemyMinions = Opponent.BoardZone.GetAll(p => !p.HasStealth && !p.IsImmune));
			}
			#endregion
		}


		/// <summary>
		/// Returns a string which dumps information about this player.
		/// </summary>
		/// <returns></returns>
		public string FullPrint()
		{
			var str = new StringBuilder();
			str.Append($"{Name}[Mana:{RemainingMana}/{OverloadOwed}/{BaseMana}][{OverloadLocked}]");
			//str.Append($"[ENCH {OldEnchants.Count}]");
			//str.Append($"[TRIG {Triggers.Count}]");
			return str.ToString();
		}
	}

	public partial class Controller
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal void CleanTurnStatistics()
		{
			_attrs.ClearTurnStatistics();
		}

		internal override void ApplyEffect(AbstractEffect effect)
		{
			effect.ApplyTo(this);
		}
		internal override void RemoveEffect(AbstractEffect effect)
		{
			effect.RemoveFrom(this);
		}
	}
}
