#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion
using System;
using System.Collections;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
//using Newtonsoft.Json;
using SabberStoneCore.Enchants;
using SabberStoneCore.Model;
using SabberStoneCore.src.Loader;
using SabberStoneCore.CardSets.Classic;
//using SabberStoneCore.Properties;

namespace SabberStoneCore.src.Loader
{
	internal class CardContainer : IReadOnlyCollection<Card>
	{
		/// <summary>The cards container</summary>
		/// <autogeneratedoc />
		internal FrozenDictionary<string, Card> Cards { get; private set; }

		/// <summary>Gets the <see cref="Card"/> with the specified card identifier.</summary>
		/// <value>The <see cref="Card"/>.</value>
		/// <param name="cardId">The card identifier.</param>
		/// <returns></returns>
		/// <autogeneratedoc />
		internal Card this[string cardId] => Cards[cardId];

		internal static FrozenDictionary<string, CardDef> GetCardDefs()
		{
			Dictionary<string, CardDef> cards = [];
			VanillaCardsGen.AddAll(cards);

			return cards.ToFrozenDictionary();
		}

		internal void Load(IEnumerable<Card> cards, IEnumerable<string> excludeIds)
		{
			var excludes = excludeIds.ToFrozenSet();

			// Set cards (without behaviours)
			Cards = (from c in cards where !excludes.Contains(c.Id) select new { Key = c.Id, Value = c }).ToFrozenDictionary(x => x.Key, x => x.Value);

			FrozenDictionary<string, CardDef> cardDefs = GetCardDefs();

			// Add Powers
			foreach (Card c in Cards.Values)
			{
				if (Powers.Instance.Get.TryGetValue(c.Id, out Power power))
				{
					//// fill missing playrequirements, last card def with info is CardDefs-36393.xml
					//if (cardDef.PlayReqs != null)
					//{
					//	c.SetPlayRequirements(cardDef.PlayReqs);
					//}

					//// fill missing entourage, last card def with info is CardDefs-36393.xml
					//if (cardDef.Entourage != null)
					//{
					//	c.Entourage = cardDef.Entourage;
					//}

					c.Power = power;
					c.Implemented = power == null ||
									power.PowerTask != null ||
									power.DeathrattleTask != null ||
									power.ComboTask != null ||
									power.TopdeckTask != null ||
									power.OverkillTask != null ||
									power.Aura != null ||
									power.Trigger != null ||
									power.Enchant != null;
				}

				if (cardDefs.TryGetValue(c.Id, out CardDef? cardDef))
				{
					if (cardDef.PlayReqs != null)
						c.SetPlayRequirements(cardDef.PlayReqs);
					if (cardDef.Entourage != null)
						c.Entourage = cardDef.Entourage;
				}
			}
		}

		public IEnumerator<Card> GetEnumerator()
		{
			return ((IReadOnlyCollection<Card>)Cards.Values).GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public int Count => Cards.Count;
	}
}
