#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion
using System;
using SabberStoneCore.Enchants;
using SabberStoneCore.Enums;

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// The entity representing the player.
	/// </summary>
	/// <seealso cref="Character" />
	/// <autogeneratedoc />
	public partial class Hero : Character
	{
		/// <summary>Initializes a new instance of the <see cref="Hero"/> class.</summary>
		/// <param name="controller">Owner of the character; not specifically limited to players.</param>
		/// <param name="card">The card which this character embodies.</param>
		/// <param name="tags">Properties of this entity.</param>
		/// <autogeneratedoc />
		public Hero(in Controller controller, in Card card, in int id = -1)
			: base(in controller, in card, in id)
		{
			Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Hero", !Game.Logging? "":$"{card.Name} ({card.Class}) was created.");
		}

		/// <summary>
		/// A copy constructor.
		/// </summary>
		/// <param name="controller">The target <see cref="T:SabberStoneCore.Model.Entities.Controller" /> instance.</param>
		/// <param name="hero">The source <see cref="T:SabberStoneCore.Model.Entities.Hero" />.</param>
		protected Hero(in Controller controller, Hero hero) : base(in controller, hero)
		{
		}

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
		public virtual int Armor { get; set; }

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

		#region Overrides of Playable

		public override void Destroy()
		{
			throw new NotImplementedException();
		}

		#endregion

		#region Overrides of Character

		public override int TakeDamage(Playable source, int damage)
		{
			throw new NotImplementedException();
		}

		internal override bool GetAttribute(BoolAttributes attr)
		{
			throw new NotImplementedException();
		}

		internal override void SetAttribute(BoolAttributes attr, bool value)
		{
			throw new NotImplementedException();
		}

		#endregion
	}

	public partial class Hero
	{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

		//public int SpellPowerDamage => this[GameTag.CURRENT_SPELLPOWER];

		#region Overrides of Playable

		public override Playable Clone(in Controller controller)
		{
			return new Hero(in controller, this);
		}

		#endregion
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
		internal override ref bool GetRef(int index)
		{
			throw new NotImplementedException();
		}

		internal override ref int GetIntRef(int index)
		{
			throw new NotImplementedException();
		}
	}
}
