#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion

using System;
using SabberStoneCore.Enchants;
using SabberStoneCore.Enums;
using SabberStoneCore.Model.Zones;

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// Entity which is a character that can reside in the <see cref="Controller.BoardZone"/> and perform
	/// certain actions (provided through <see cref="Character"/>.
	/// </summary>
	/// <seealso cref="Character" />
	public partial class Minion : Character
	{
		/// <summary>Initializes a new instance of the <see cref="Minion"/> class.</summary>
		/// <param name="controller">Owner of the character; not specifically limited to players.</param>
		/// <param name="card">The card which this character embodies.</param>
		/// <param name="tags">Properties of this entity.</param>
		/// <autogeneratedoc />
		public Minion(in Controller controller, in Card card, in EntityData tags, in int id = -1)
			: base(in controller, in card, in tags, in id)
		{
			Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Minion", !Game.Logging? "":$"{this} ({Card.Class}) was created.");
		}

		///// <summary>
		///// A copy constructor.
		///// </summary>
		///// <param name="controller">The target <see cref="Controller"/> instance.</param>
		///// <param name="minion">The source <see cref="Minion"/>.</param>
		protected internal Minion(in Controller controller, Minion minion) : base(in controller, minion) { }

		internal override bool GetAttribute(BoolAttributes attr)
		{
			throw new NotImplementedException();
		}

		internal override void SetAttribute(BoolAttributes attr, bool value)
		{
			throw new NotImplementedException();
		}

		/// <summary>Character can attack.</summary>
		/// <autogeneratedoc />
		//public override bool CanAttack(bool checkTargets) => base.CanAttack && AttackDamage > 0 && !Untouchable;

		/// <summary>
		/// Gets the Minions adjacent to this Minion in order from left to right.
		/// </summary>
		/// <param name="includeUntouchables">true if the result should contain Untouchable entities.</param>
		public Minion[] GetAdjacentMinions(bool includeUntouchables = false)
		{
			int pos = ZonePosition;
			if (!(Zone is BoardZone zone))
				throw new MethodAccessException();

			if (includeUntouchables)
			{
				if (pos > 0)
				{
					if (pos < zone.Count - 1)
					{
						var arr = new Minion[2];
						arr[0] = zone[pos - 1];
						arr[1] = zone[pos + 1];
						return arr;
					}
					return new[] { zone[pos - 1] };
				}
				return pos < zone.Count - 1 ?
					new[] { zone[pos + 1] } :
					new Minion[0];
			}


			if (pos > 0)
			{
				Minion left;
				if (pos < zone.Count - 1)
				{
					left = zone[pos - 1];
					Minion right = zone[pos + 1];
					return left.Untouchable
						? (right.Untouchable ? new Minion[0] : new[] {right})
						: (right.Untouchable ? new[] {left} : new[] {left, right});
				}

				left = zone[pos - 1];
				return left.Untouchable ? new Minion[0] : new [] {left};
			}

			if (pos < zone.Count - 1)
			{
				Minion r = zone[pos + 1];
				return r.Untouchable ? new Minion[0] : new[] {r};
			}

			return new Minion[0];
		}

		public override void Destroy()
		{
			throw new NotImplementedException();
		}

		/// <summary>
		/// Gets a value indicating whether this entity is playable by the player. Some entities require specific
		/// requirements before they can be played. This method will process the requirements and produce
		/// a result for the current state of the game.
		/// </summary>
		/// <value><c>true</c> if this entity is playable; otherwise, <c>false</c>.</value>
		public override bool IsPlayableByPlayer()
		{
			// check if we got a slot on board for minions
			if (Controller.BoardZone.IsFull)
			{
				Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
					!Game.Logging ? "" : $"{this} isn't playable, because not enough place on board.");
				return false;
			}

			return base.IsPlayableByPlayer();
		}

		public override Playable Clone(in Controller controller)
		{
			return new Minion(in controller, this);
		}

		internal void ResetAttributes()
		{
			_numAttackThisTurn = 0;
			_damage = 0;
			_modifiedATK = null;
			_modifiedHealth = null;
			_modifiedCost = null;
			_modifiedStealth = null;
			_modifiedTaunt = null;
			_modifiedCantBeTargetedBySpells = null;
		}
	}

	public partial class Minion
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public virtual bool HasDivineShield
		{
			get => Card.DivineShield;
			set => throw new NotImplementedException();
		}

		public virtual bool HasDeathrattle
		{
			get => Card.Deathrattle;
			set => throw new NotImplementedException();
		}
		public virtual bool HasCharge
		{
			get => Card.Charge;
			set => throw new NotImplementedException();
		}
		public virtual bool IsRush
		{
			get => Card.Rush;
			set => throw new NotImplementedException();
		}

		public bool HasInspire => Card[GameTag.INSPIRE] == 1;

		//public bool IsEnraged
		//{
		//	get { return this[GameTag.ENRAGED] == 1; }
		//	set { this[GameTag.ENRAGED] = value ? 1 : 0; }
		//}

		public bool Freeze => Card.Freeze;

		public bool Untouchable => Card.Untouchable;

		//public int LastBoardPosition
		//{
		//	get
		//	{
		//		_data.TryGetValue(GameTag.TAG_LAST_KNOWN_POSITION_ON_BOARD, out int value);
		//		return value;
		//	}
		//	set { this[GameTag.TAG_LAST_KNOWN_POSITION_ON_BOARD] = value; }
		//}

		//public override ref bool this[BoolAttributes attr]
		//{
		//	get;
		//}

		internal override ref bool GetRef(int index)
		{
			throw new NotImplementedException();
		}

		internal override ref int GetIntRef(int index)
		{
			throw new NotImplementedException();
		}
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
