using System;
using System.Collections.Generic;
using SabberStoneCore.Enums;
using SabberStoneCore.Model.Zones;
using SabberStoneCore.Tasks.SimpleTasks;

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// Entity which is a character that can reside in the <see cref="Controller.BoardZone"/> and perform
	/// certain actions (provided through <see cref="Character"/>.
	/// </summary>
	/// <seealso cref="Character" />
	public partial class Minion : Character
	{
		/// <summary>Initializes a new instance of the <see cref="Minion"/> class.</summary>
		/// <param name="controller">Owner of the character; not specifically limited to players.</param>
		/// <param name="card">The card which this character embodies.</param>
		/// <param name="tags">Properties of this entity.</param>
		/// <autogeneratedoc />
		public Minion(in Controller controller, in Card card, in EntityData tags, in int id = -1)
			: base(in controller, in card, in tags, in id)
		{
			Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Minion", !Game.Logging? "":$"{this} ({Card.Class}) was created.");
		}

		///// <summary>
		///// A copy constructor.
		///// </summary>
		///// <param name="controller">The target <see cref="Controller"/> instance.</param>
		///// <param name="minion">The source <see cref="Minion"/>.</param>
		protected internal Minion(in Controller controller, Minion minion) : base(in controller, minion) { }

		internal override bool GetAttribute(Attributes attr)
		{
			throw new NotImplementedException();
		}

		internal override void SetAttribute(Attributes attr, bool value)
		{
			throw new NotImplementedException();
		}

		/// <summary>Character can attack.</summary>
		/// <autogeneratedoc />
		public override bool CanAttack => base.CanAttack && AttackDamage > 0 && !Untouchable;

		/// <summary>
		/// Gets the Minions adjacent to this Minion in order from left to right.
		/// </summary>
		/// <param name="includeUntouchables">true if the result should contain Untouchable entities.</param>
		public Minion[] GetAdjacentMinions(bool includeUntouchables = false)
		{
			int pos = ZonePosition;
			if (!(Zone is BoardZone zone))
				throw new MethodAccessException();

			if (includeUntouchables)
			{
				if (pos > 0)
				{
					if (pos < zone.Count - 1)
					{
						var arr = new Minion[2];
						arr[0] = zone[pos - 1];
						arr[1] = zone[pos + 1];
						return arr;
					}
					return new[] { zone[pos - 1] };
				}
				return pos < zone.Count - 1 ?
					new[] { zone[pos + 1] } :
					new Minion[0];
			}


			if (pos > 0)
			{
				Minion left;
				if (pos < zone.Count - 1)
				{
					left = zone[pos - 1];
					Minion right = zone[pos + 1];
					return left.Untouchable
						? (right.Untouchable ? new Minion[0] : new[] {right})
						: (right.Untouchable ? new[] {left} : new[] {left, right});
				}

				left = zone[pos - 1];
				return left.Untouchable ? new Minion[0] : new [] {left};
			}

			if (pos < zone.Count - 1)
			{
				Minion r = zone[pos + 1];
				return r.Untouchable ? new Minion[0] : new[] {r};
			}

			return new Minion[0];
		}

		public override void Destroy()
		{
			throw new NotImplementedException();
		}

		/// <summary>
		/// Gets a value indicating whether this entity is playable by the player. Some entities require specific
		/// requirements before they can be played. This method will process the requirements and produce
		/// a result for the current state of the game.
		/// </summary>
		/// <value><c>true</c> if this entity is playable; otherwise, <c>false</c>.</value>
		public override bool IsPlayableByPlayer
		{
			get
			{
				// check if we got a slot on board for minions
				if (Controller.BoardZone.IsFull)
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
						!Game.Logging? "":$"{this} isn't playable, because not enough place on board.");
					return false;
				}

				return base.IsPlayableByPlayer;
			}
		}

		public override Playable Clone(in Controller controller)
		{
			return new Minion(in controller, this);
		}
	}

	public partial class Minion
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public virtual bool HasDivineShield
		{
			get => Card.DivineShield;
			set => throw new NotImplementedException();
		}

		public virtual bool HasDeathrattle
		{
			get => Card.Deathrattle;
			set => throw new NotImplementedException();
		}
		public virtual bool HasCharge
		{
			get => Card.Charge;
			set => throw new NotImplementedException();
		}
		public virtual bool IsRush
		{
			get => Card.Rush;
			set => throw new NotImplementedException();
		}

		public bool HasBattleCry
		{
			get { return Card[GameTag.BATTLECRY] != 0; }
			set { this[GameTag.BATTLECRY] = value ? 1 : 0; }
		}

		public bool HasInspire
		{
			get { return this[GameTag.INSPIRE] == 1; }
			set { this[GameTag.INSPIRE] = value ? 1 : 0; }
		}

		public bool IsEnraged
		{
			get { return this[GameTag.ENRAGED] == 1; }
			set { this[GameTag.ENRAGED] = value ? 1 : 0; }
		}

		public bool Freeze => Card.Freeze;

		public bool Untouchable => Card.Untouchable;

		public int LastBoardPosition
		{
			get
			{
				_data.TryGetValue(GameTag.TAG_LAST_KNOWN_POSITION_ON_BOARD, out int value);
				return value;
			}
			set { this[GameTag.TAG_LAST_KNOWN_POSITION_ON_BOARD] = value; }
		}

		internal override ref bool GetRef(int index)
		{
			throw new NotImplementedException();
		}
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
