using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SabberStoneCore.Auras;
using SabberStoneCore.Enums;
using SabberStoneCore.Enchants;
using SabberStoneCore.Tasks;

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// Base implementation of the <see cref="Playable"/> interface.
	/// </summary>
	/// <seealso cref="Playable" />
	/// <seealso cref="Entity"/>
	public abstract partial class Playable : Entity
	{
		/// <summary>Initializes a new instance of the <see cref="Playable"/> class.</summary>
		/// <param name="controller">The controller.</param>
		/// <param name="card">The card.</param>
		/// <param name="tags">The tags.</param>
		/// <autogeneratedoc />
		protected Playable(in Controller controller, in Card card, in EntityData tags, in int id)
			: base(controller.Game, in card, in tags, in id)
		{
			Controller = controller;

			if (_history)
				tags[GameTag.CONTROLLER] = controller.PlayerId;
		}

		/// <inheritdoc />
		/// <summary>
		/// A copy constructor. This constructor is only used to the inherited copy constructors.
		/// </summary>
		/// <param name="controller">The target <see cref="T:SabberStoneCore.Model.Entities.Controller" /> instance.</param>
		/// <param name="playable">The source <see cref="T:SabberStoneCore.Model.Entities.Playable`1" /></param>
		protected Playable(in Controller controller, in Playable playable) : base(controller.Game, playable)
		{
			Controller = controller;

			controller.Game.IdEntityDic[playable.Id] = this;

			//playable.OngoingEffect?.Clone(this);
			playable.ActivatedTrigger?.Activate(controller.Game, this, cloning: true);

			// Cloning applied enchantments.
			{
				List<Enchantment> originalEnchantments = playable.AppliedEnchantments;
				if (originalEnchantments != null)
				{
					var enchantments = new List<Enchantment>(originalEnchantments.Count);
					foreach (Enchantment p in originalEnchantments)
					{
						enchantments.Add((Enchantment)p.Clone(controller));
					}
					AppliedEnchantments = enchantments;
				}
			}

			if (playable.ChooseOnePlayables != null)
			{
				ChooseOnePlayables = new Playable[2];
				Array.Copy(playable.ChooseOnePlayables, ChooseOnePlayables, 2);
			}

			_v1 = playable._v1;
			_v2 = playable._v2;
			_modifiedCost = playable._modifiedCost;
			_costManager = playable._costManager?.Clone();

			//_toBeDestroyed = playable._toBeDestroyed;
			_exhausted = playable._exhausted;
			_zonePosition = playable._zonePosition;
		}

		/// <summary>
		/// Gets the set of playables necessary for the 'choose one' action
		/// invoked by this entity. This list is hardcoded into the card data of this
		/// entity.
		/// The controller must have chosen one of these playables
		/// before this entity can be moved into <see cref="F:SabberStoneCore.Enums.Zone.PLAY" />.
		/// </summary>
		/// <value>Playables to choose from.</value>
		/// <autogeneratedoc />
		public Playable[] ChooseOnePlayables { get; set; }

		/// <summary>
		/// Gets or sets Ongoing effect of this entity.
		/// Ongoing effects are minion, weapon, and boss Hero Power abilities
		/// which grant special effects on an ongoing basis.
		/// Ongoing effects are often referred to as auras, particularly
		/// those which grant temporary enchantments to other targets.
		/// https://hearthstone.gamepedia.com/Ongoing_effect
		/// Here, OngoingEffect includes <see cref="OngoingEnchant"/> too.
		/// </summary>
		public IAura OngoingEffect
		{
			get => _ongoingEffect;
			set => _ongoingEffect = value;
		}

		/// <summary>
		/// Gets or sets current activated <see cref="Trigger"/> of this entity.
		/// Nullifying this field does not mean deactivation of the trigger.
		/// Use <see cref="Trigger.Remove()"/> instead.
		/// </summary>
		public Trigger ActivatedTrigger
		{
			get => _activatedTrigger;
			set => _activatedTrigger = value;
		}

		/// <summary>
		/// Gets or sets the Powers attached to this entity.
		/// These Powers are hardcoded into the card data, from which this entity
		/// is constructed.
		/// </summary>
		/// <value>
		/// <see cref="T:SabberStoneCore.Enchants.Power" />
		/// </value>
		/// <autogeneratedoc />
		//public List<Power> Powers => Card.Powers;
		public Power Power => Card.Power;

		public void ActivateTask(in PowerActivation activation = PowerActivation.POWER, in Character target = null, in int chooseOne = 0, in Playable source = null)
		{
			if (ChooseOne)
			{
				if (Controller.ChooseBoth
				    && !Card.Id.Equals("EX1_165")	// OG_044a, using choose one 0 option
				    && !Card.Id.Equals("BRM_010")	// OG_044b, using choose one 0 option
				    && !Card.Id.Equals("AT_042")	// OG_044c, using choose one 0 option
					&& !Card.Id.Equals("UNG_101")	// UNG_101t3
					&& !Card.Id.Equals("ICC_051")	// ICC_051t3
					&& !Card.Id.Equals("ICC_047"))	// using choose one 0 option
				{
					ChooseOnePlayables[0].ActivateTask(activation, target, chooseOne, this);
					ChooseOnePlayables[1].ActivateTask(activation, target, chooseOne, this);
					return;
				}

				if (!Controller.ChooseBoth && chooseOne > 0)
				{
					ChooseOnePlayables[chooseOne - 1].ActivateTask(activation, target, chooseOne, this);
					return;
				}
			}

			if (Power == null) return;

			ISimpleTask task = null;
			switch (activation)
			{
				case PowerActivation.POWER:
					task = Power.PowerTask;
					break;
				case PowerActivation.DEATHRATTLE:
					task = Power.DeathrattleTask;
					break;
				case PowerActivation.COMBO:
					task = Power.ComboTask;
					break;
			}
			if (task == null) return;

			// clone task here
			//ISimpleTask clone = task.Clone();
			//clone.Game = source?.Game ?? Game;
			//clone.Controller = source?.Controller ?? Controller;
			//clone.Source = source ?? this;
			//clone.Target = target;

			if (source != null)
			{
				source.Game.TaskQueue.Enqueue(in task, source.Controller, source, target);
			}
			else
				Game.TaskQueue.Enqueue(in task, Controller, this, target);
		}

		/// <summary>
		/// Stores the next Order Of Play index held by the <see cref="T:SabberStoneCore.Model.Game" /> instance.
		/// Order of play is important because it's the order in which effects are resolved.
		/// </summary>
		/// <param name="type">The type of this entity, stringified.</param>
		/// <autogeneratedoc />
		//public void SetOrderOfPlay(string type)
		//{
		//	if (type.Equals("PLAY")
		//	 || type.Equals("SECRET_OR_QUEST")
		//	 || type.Equals("WEAPON"))
		//	{
		//		OrderOfPlay = Game.NextOop;
		//	}
		//}

		/// <summary>Mark this entity for destruction.</summary>
		/// <returns>Returns itself.</returns>
		/// <autogeneratedoc />
		public abstract void Destroy();

		/// <summary>
		/// Gets a value indicating whether this entity is playable. Some entities require specific
		/// requirements before they can be played. This method will process the requirements and produce
		/// a result for the current state of the game.
		/// </summary>
		/// <value><c>true</c> if this entity is playable; otherwise, <c>false</c>.</value>
		/// <autogeneratedoc />
		public bool IsPlayable => IsPlayableByPlayer && IsPlayableByCardReq;

		/// <summary>
		/// Gets a value indicating whether this entity is playable by player. Dynamic requirements
		/// are checked, eg: If a spell costs health instead of mana, this method will return <c>false</c>
		/// if the health cost would be higher than the available health.
		/// </summary>
		/// <value><c>true</c> if this entity is playable by player; otherwise, <c>false</c>.</value>
		/// <autogeneratedoc />
		public virtual bool IsPlayableByPlayer
		{
			get
			{
				if (Card.HideStat)
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
						!Game.Logging ? "" : $"{this} isn't playable, because can't play card with HIDE_STAT");
					return false;
				}

				// check if player has enough mana to play card
				bool bool1 = (this is Spell && Controller.ControllerAuraEffects[GameTag.SPELLS_COST_HEALTH] == 1);
				bool bool2 = AuraEffects?.CardCostHealth ?? false;
				if ((!bool1 && !bool2) && Controller.RemainingMana < Cost)
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
						!Game.Logging ? "" : $"{this} isn't playable, because not enough mana to pay cost.");
					return false;
				}

				// check if player is on turn
				if (Controller != Game.CurrentPlayer)
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
						!Game.Logging ? "" : $"{this} isn't playable, because player not on turn.");
					return false;
				}

				// check if entity is in hand to be played
				if (Zone != Controller.HandZone && !(this is HeroPower))
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable",
						!Game.Logging ? "" : $"{this} isn't playable, because card not in hand.");
					return false;
				}

				return true;
			}
		}

		/// <summary>
		/// Gets a value indicating whether this entity is playable by card requirements.
		/// Static requirements are checked.
		/// </summary>
		/// <value><c>true</c> if this entity is playable by card requirements; otherwise, <c>false</c>.</value>
		/// <autogeneratedoc />
		public bool IsPlayableByCardReq
		{
			get
			{
				// check requirements on cards here 
				if (!Card.IsPlayableByCardReq(Controller))
				{
					if (_logging)
					{
						foreach (KeyValuePair<PlayReq, int> item in Card.PlayRequirements)
						{
							PlayReq req = item.Key;
							int param = item.Value;

							Game.Log(LogLevel.DEBUG, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"{this} check PlayReq {req} ... !");

							switch (req)
							{
								case PlayReq.REQ_NUM_MINION_SLOTS:
									{
										if (Controller.BoardZone.IsFull)
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"Board is full can't summon new minion.");
											return false;
										}
										break;
									}
								case PlayReq.REQ_ENTIRE_ENTOURAGE_NOT_IN_PLAY:
									{
										var ids = Controller.BoardZone.Select(p => p.Card.Id).ToList();
										bool containsAll = true;
										for (int i = 0; i < Card.Entourage.Length; i++)
											containsAll &= ids.Contains(Card.Entourage[i]);

										if (containsAll)
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"All ready all entourageing cards summoned.");
											return false;
										}
										break;
									}
								case PlayReq.REQ_WEAPON_EQUIPPED:
									{
										if (Controller.Hero.Weapon == null)
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"Need a weapon to play this card.");
											return false;
										}
										break;
									}
								case PlayReq.REQ_MINIMUM_ENEMY_MINIONS:
									{
										if (Controller.Opponent.BoardZone.Count < param)
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"Need at least {param} enemy minions to play this card.");
											return false;
										}
										break;
									}
								case PlayReq.REQ_MINIMUM_TOTAL_MINIONS:
									{
										if (Controller.BoardZone.Count + Controller.Opponent.BoardZone.Count < param)
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"Need at least {param} minions to play this card.");
											return false;
										}
										break;
									}
								case PlayReq.REQ_STEADY_SHOT:
									{
										if (!Controller.Hero.HeroPower.Card.Id.Equals("DS1h_292"))
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"Need steady shoot to be used.");
											return false;
										}
										break;
									}

								case PlayReq.REQ_FRIENDLY_MINION_DIED_THIS_GAME:
									{
										if (!Controller.GraveyardZone.Any(p => p is Minion m && m.ToBeDestroyed))
										{
											Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"No friendly minions died this game.");
											return false;
										}
										break;
									}

								// implemented in Targeting
								case PlayReq.REQ_TARGET_FOR_COMBO:
								case PlayReq.REQ_FROZEN_TARGET:
								case PlayReq.REQ_MINION_OR_ENEMY_HERO:
								case PlayReq.REQ_TARGET_MAX_ATTACK:
								case PlayReq.REQ_MINION_TARGET:
								case PlayReq.REQ_FRIENDLY_TARGET:
								case PlayReq.REQ_ENEMY_TARGET:
								case PlayReq.REQ_UNDAMAGED_TARGET:
								case PlayReq.REQ_DAMAGED_TARGET:
								case PlayReq.REQ_TARGET_WITH_RACE:
								case PlayReq.REQ_MUST_TARGET_TAUNTER:
								case PlayReq.REQ_TARGET_MIN_ATTACK:
								case PlayReq.REQ_TARGET_WITH_DEATHRATTLE:
								case PlayReq.REQ_TARGET_WITH_BATTLECRY:
								case PlayReq.REQ_TARGET_IF_AVAILABLE_AND_DRAGON_IN_HAND:
								case PlayReq.REQ_TARGET_IF_AVAILABE_AND_ELEMENTAL_PLAYED_LAST_TURN:
								case PlayReq.REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_MINIONS:
								case PlayReq.REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_SECRETS:
								case PlayReq.REQ_NONSELF_TARGET:
									break;

								// already implemented ... card.RequiresTarget and RequiresTargetIfAvailable
								case PlayReq.REQ_TARGET_TO_PLAY:
								case PlayReq.REQ_TARGET_IF_AVAILABLE:
									break;

								default:
									Game.Log(LogLevel.ERROR, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"PlayReq {req} not in switch needs to be added (Playable)!");
									break;
							}
						}
					}

					return false;
				}

				// check if we need a target and there are some
				if (Card.MustHaveTargetToPlay && !HasAnyValidPlayTargets)
				{
					Game.Log(LogLevel.VERBOSE, BlockType.PLAY, "Playable", !Game.Logging ? "" : $"{this} isn't playable, because need valid target and we don't have one.");
					return false;
				}

				return true;
			}
		}

		public abstract Playable Clone(in Controller controller);

		public override string Hash(params GameTag[] ignore)
		{
			if (ActivatedTrigger == null)
				return base.Hash(ignore);

			var str = new StringBuilder(base.Hash(ignore));
			if (ActivatedTrigger != null)
			{
				str.Append("[TR:");
				str.Append(ActivatedTrigger);
				str.Append("]");
			}

			//if (OngoingEffect != null)
			//{
			//	str.Append("[OE:");
			//	str.Append(OngoingEffect);
			//	str.Append("]");
			//}
			return str.ToString();
		}
	}

	public abstract partial class Playable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		internal int? _v1;
		internal int? _v2;

		protected IAura _ongoingEffect;
		protected Trigger _activatedTrigger;

		protected bool _exhausted;
		protected int _zonePosition;
		public override void Reset()
		{
			_v1 = null;
			_v2 = null;
			_exhausted = false;
			//ResetCost();
			base.Reset();
		}

		public int ZonePosition
		{
			get => _zonePosition;
			set
			{
				_zonePosition = value;
				if (_history)
					this[GameTag.ZONE_POSITION] = value + 1;
			}
		}

		public bool Combo => Card.Combo;

		public bool ChooseOne => Card.ChooseOne;

		//public bool JustPlayed
		//{
		//	get { return this[GameTag.JUST_PLAYED] == 1; }
		//	set { this[GameTag.JUST_PLAYED] = value ? 1 : 0; }
		//}

		//public bool IsSummoned
		//{
		//	get { return this[GameTag.SUMMONED] == 1; }
		//	set { this[GameTag.SUMMONED] = value ? 1 : 0; }
		//}

		public bool IsExhausted
		{
			get => _exhausted;
			set
			{
				_exhausted = value;
				if (_history || _logging)
				{
					this[GameTag.EXHAUSTED] = value ? 1 : 0;
				}
			}
		}

		public int Overload => Card.Overload;

		public bool IsEcho
		{
			get
			{
				if (AuraEffects?.Echo ?? false)
					return true;
				return Card.Echo;
			}
		}

		public virtual bool HasLifesteal
		{
			get => Card.LifeSteal;
			set => throw new NotImplementedException();
		}

		internal static ApplyingEffect GetFunction(GameTag tag, EffectOperator @operator, int value)
		{
			switch (tag)
			{
				case GameTag.ATK:
					switch (@operator)
					{
						case EffectOperator.ADD:
							return p =>
							{
								ref int? target = ref p._v1;
								int v = target ?? p.Card.ATK;
								target = v + value;
							};
						case EffectOperator.SUB:
							return p =>
							{
								ref int? target = ref p._v1;
								int v = target ?? p.Card.ATK;
								target = v - value;
							};
						case EffectOperator.MUL:
							return p =>
							{
								ref int? target = ref p._v1;
								int v = target ?? p.Card.ATK;
								target = v * value;
							};
						case EffectOperator.SET:
							return p =>
							{
								for (int i = p.Game.OneTurnEffects.Count - 1; i >= 0; i--)
								{
									(int id, IEffect eff) = p.Game.OneTurnEffects[i];
									if (id != p.Id || !(eff is GenericEffect<Character>)) continue;
									p.Game.OneTurnEffects.RemoveAt(i);
								}

								p._v1 = value;
							};
						default:
							throw new ArgumentOutOfRangeException(nameof(@operator), @operator, null);
					}
				case GameTag.HEALTH:
					switch (@operator)
					{
						case EffectOperator.ADD:
							return p =>
							{
								ref int? target = ref p._v2;
								int v = target ?? p.Card.Health;
								target = v + value;
							};
						case EffectOperator.SUB:
							return p =>
							{
								ref int? target = ref p._v2;
								int v = target ?? p.Card.Health;
								target = v - value;
							};
						case EffectOperator.MUL:
							return p =>
							{
								ref int? target = ref p._v2;
								int v = target ?? p.Card.Health;
								target = v * value;
							};
						case EffectOperator.SET:
							return p =>
							{
								if (p is HeroInPlay h)
								{
									int hbh = h.BaseHealth;
									if (hbh > value)
										h.Damage = hbh - value;
									else
										h.Health = value;
									return;
								}

								if (p is MinionInPlay m)
								{
									m.Health = value;
								}
							};
						default:
							throw new ArgumentOutOfRangeException(nameof(@operator), @operator, null);
					}
				case GameTag.COST:
					switch (@operator)
					{
						case EffectOperator.ADD:
							return p =>
							{
								ref int? target = ref p._modifiedCost;
								int v = target ?? p.Card.Cost;
								target = v + value;
								p._costManager?.AddCostEnchantment(@operator, value);
							};
						case EffectOperator.SUB:
							return p =>
							{
								ref int? target = ref p._modifiedCost;
								int v = target ?? p.Card.Cost;
								target = v - value;
								p._costManager?.AddCostEnchantment(@operator, value);
							};
						case EffectOperator.MUL:
							return p =>
							{
								ref int? target = ref p._modifiedCost;
								int v = target ?? p.Card.Cost;
								target = v * value;
								p._costManager?.AddCostEnchantment(@operator, value);
							};
						case EffectOperator.SET:
							return p =>
							{
								p._modifiedCost = value;
								p._costManager?.AddCostEnchantment(@operator, value);
							};
						default:
							throw new ArgumentOutOfRangeException(nameof(@operator), @operator, null);
					}
				default:
					throw new ArgumentOutOfRangeException(nameof(@operator), @operator, null);
			}
		}

		//internal virtual bool GetBoolAttribute(Attributes attribute) => throw new NotImplementedException();
		//internal virtual int GetIntAttribute(Attributes attribute) => throw new NotImplementedException();
		private static void AddAttackDamage(Playable p, int value) => p._v1 += value;
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
