#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion
﻿using System;
using SabberStoneCore.Enums;
using System.Collections.Generic;
using SabberStoneCore.Kettle;

namespace SabberStoneCore.Model.Entities
{
	/// <summary>
	/// Entity which can be attached to a <see cref="Hero"/>.
	/// A weapon is comparable to a buff, because it gives more/stronger abilities to the
	/// controller's hero for a limited use.
	/// </summary>
	/// <seealso cref="Playable" />
	public class Weapon : Character
	{
		/// <summary>Initializes a new instance of the <see cref="Weapon"/> class.</summary>
		/// <param name="controller">The controller.</param>
		/// <param name="card">The card.</param>
		/// <param name="tags">The tags.</param>
		/// <autogeneratedoc />
		public Weapon(in Controller controller, in Card card, in EntityData tags, in int id = -1)
			: base(in controller, in card, in tags, in id)
		{
			_v1 = card.ATK;
			_v2 = card[GameTag.DURABILITY];
			_attrs = new Attributes(in card);

			Game.Log(LogLevel.INFO, BlockType.PLAY, "Weapon", !Game.Logging? "":$"{this} ({Card.Class}) was created.");
		}

		/// <summary>
		/// A copy constructor.
		/// </summary>
		/// <param name="controller">A target <see cref="Controller"/> instance.</param>
		/// <param name="weapon">A source <see cref="Weapon"/>.</param>
		private Weapon(in Controller controller, Weapon weapon) : base(in controller, weapon)
		{
			_attrs = weapon._attrs;
		}

		public override Playable Clone(in Controller controller)
		{
			return new Weapon(in controller, this);
		}

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

		public override int AttackDamage
		{
			get => _v1.Value;
			set => _v1 = value;
		}

		public int Durability
		{
			get => _v2.Value - Damage;
			set => _v2 = value;
		}

		public bool HasDeathrattle => Card.Deathrattle;

		#region Overrides of Playable

		public override void Destroy()
		{
			ToBeDestroyed = true;
		}

		#endregion

		#region Overrides of Character

		internal override ref bool GetRef(int index)
		{
			throw new NotImplementedException();
		}

		internal override bool GetAttribute(Entities.Attributes attr)
		{
			return GetRef(attr);
		}

		internal override void SetAttribute(Entities.Attributes attr, bool value)
		{
			GetRef(attr) = value;
		}

		#endregion

		#region Attributes
		private unsafe struct Attributes
		{
			// 0 : Damage

			// 0 : IsImmune
			// 1 : ToBeDestroyed
			// 2 : Poisonous
			// 3 : Lifesteal
			private const int NUM_INT_ATTRS = 1;
			private const int NUM_BOOL_ATTRS = 4;
#pragma warning disable 649
			public fixed int intAttrs[NUM_INT_ATTRS];
			public fixed bool boolAttrs[NUM_BOOL_ATTRS];
#pragma warning restore 649

			public Attributes(in Card card)
			{
				boolAttrs[2] = card.Poisonous;
				boolAttrs[3] = card.LifeSteal;
			}
		}
		private Attributes _attrs;
		public override unsafe int Damage
		{
			get => _attrs.intAttrs[0];
			set
			{
				_attrs.intAttrs[0] = value;
				if (_v2 <= value)
					ToBeDestroyed = true;
			}
		}

		public override unsafe bool IsImmune
		{
			get => (AuraEffects?.Immune ?? false) ||
			       _attrs.boolAttrs[0];
			set => _attrs.boolAttrs[0] = value;
		}

		public override unsafe bool ToBeDestroyed
		{
			get => _attrs.boolAttrs[1];
			set
			{
				_attrs.boolAttrs[1] = value;
				if (value)
					Game.ClearWeapons += Controller.Hero.RemoveWeapon;
			}
		}

		public override unsafe bool Poisonous
		{
			get => _attrs.boolAttrs[2];
			set => _attrs.boolAttrs[2] = value;
		}
		public override unsafe bool HasLifesteal
		{
			get => _attrs.boolAttrs[3];
			set => _attrs.boolAttrs[3] = value;
		}

		private unsafe ref bool GetRef(Entities.Attributes attr)
		{
			switch (attr)
			{
				case Entities.Attributes.Immune:
					return ref _attrs.boolAttrs[0];
				case Entities.Attributes.ToBeDestroyed:
					return ref _attrs.boolAttrs[1];
				case Entities.Attributes.Poisonous:
					return ref _attrs.boolAttrs[2];
				case Entities.Attributes.Lifesteal:
					return ref _attrs.boolAttrs[3];
				default:
					throw new NotImplementedException();
			}
		}
		#endregion
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
